name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Angular Deploy gh-pages Actions
        # You may pin to the exact commit or the version.
        # uses: AhsanAyaz/angular-deploy-gh-pages-actions@26ffbdb76b46ce3d649d046f1f7f45099654cfd7
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.1
        with:
          # Github access token token used to deploy on gh_pages. You can find it on Github.
          github_access_token: ${{ secrets.TOKEN }}
          # The directory of the angular project, in which all the commands will run
          angular_project_dir: "" # optional, default is ./
          # base href for the app
          base_href: "" # optional, default is /
